- hosts: kodi
  vars_files:
    - secrets.yml
  pre_tasks:
    - name: update apt packages
      apt:  update_cache=yes cache_valid_time=3600
      sudo: True
  roles:
     - { role: setup, 
         hostname: 'kodi',
         sudo: yes }


